export interface PTOData {
  recid: number;
  cancelrem: null | string;
  warcde: string;
  supprccde: null | string;
  bilnum: null | string;
  docnum: string;
  supdsc: null | string;
  trmdsc: null | string;
  shipto: null | string;
  trncde: string;
  trntot: number;
  trmcde: null | string;
  curcde: string;
  comcde: null | string;
  usrnam: string;
  currte: number;
  supcde: string;
  supadd1: null | string;
  vatamt: number;
  vatrte: number;
  othchatot: number;
  textprc: number;
  textprcfor: number;
  trntotfor: number;
  shipto2: null | string;
  othchatotfor: number;
  remarks: string;
  docapp: string;
  docbal: number;
  setdocbal: number;
  totpdc: number;
  settotpdc: number;
  amtapp: number;
  memtypcde: null | string;
  manualgl: number;
  vat: number;
  taxcde: string;
  ewtamt: number;
  pretaxamt: number;
  pretaxrte: number;
  netvatamt: number;
  ewtcde: string;
  ewtrte: number;
  ewtpaid: number;
  ewt: number;
  boramt: number;
  borcde: null | string;
  bordsc: null | string;
  docbalfor: number;
  vatableamt: number;
  vatexemptamt: number;
  vatzeroratedamt: number;
  manualvat: number;
  nonvat: number;
  chknonvat: number;
  gainloss: number;
  setdocbalfor: number;
  settotpdcfor: number;
  canceldoc: number;
  vatamtfor: number;
  netvatamtfor: number;
  vatableamtfor: number;
  vatexemptamtfor: number;
  vatzeroratedamtfor: number;
  nonvatfor: number;
  chkewt: number;
  totamtdis: number;
  totgroext: number;
  totamtdisfor: number;
  totgroextfor: number;
  netamt: number;
  netamtfor: number;
  preby: string;
  chkby: string;
  apvby: string;
  field01: null | string;
  field02: null | string;
  field03: null | string;
  field04: null | string;
  field05: null | string;
  field06: null | string;
  field07: null | string;
  field08: null | string;
  field09: null | string;
  field10: null | string;
  field11: null | string;
  field12: null | string;
  field13: null | string;
  field14: null | string;
  field15: null | string;
  field16: null | string;
  field17: null | string;
  field18: null | string;
  field19: null | string;
  field20: null | string;
  chknum: null | string;
  bnkcde: null | string;
  voudocnum: null | string;
  doclock: string;
  remarks1: null | string;
  supgrpcde: null | string;
  trndte: string;
  duedate: string;
  logdte: string;
  lastpaydte: null | string;
  canceldte: null | string;
  chkevat: number;
  evatcde: string;
  evatrte: number;
  evatamt: number;
  manualevat: number;
  advdoc: number;
  gldepcde: null | string;
  refnum: null | string;
  logtim: string;
  rcvdte: null | string;
  savingstat: string;
  intnum: string;
  posteddte: null | string;
  rcvby: string;
  deldte: string;
  rcvfrm: string;
  pdtopen: string;
  warcdenum: string;
  warloccde: string;
  ptostat: string;
  postdte: null | string;
  trntypcde: string;
  warcde2: string;
  validated: boolean;
  posted: boolean;
}
